### ISSUE TITLE
Unable to open already-opened shared memory on macOS Aarch64

### ISSUE THREAD

**Issue by magneticflux-** [magneticflux-/jvm-shared-memory#11]
Sample log:
```
com.skaggsm.sharedmemory.SharedMemoryTest > Given a shared memory reference, when another reference to the same name is reopened, then both are usable FAILED
    java.lang.AssertionError: Property failed after 1 attempts

    Repeat this test by using seed -1077834448824682046

    Caused by RuntimeException: Unusual failure of shm_open with O_RDWR! Message: Permission denied
        at com.skaggsm.sharedmemory.SharedMemoryTest$1$4.invokeSuspend(SharedMemoryTest.kt:69)
        at com.skaggsm.sharedmemory.SharedMemoryTest$1$4.invoke(SharedMemoryTest.kt)
        at com.skaggsm.sharedmemory.SharedMemoryTest$1$4.invoke(SharedMemoryTest.kt)

        Caused by:
        java.lang.AssertionError: Property failed after 1 attempts

        Repeat this test by using seed -1077834448824682046

        Caused by RuntimeException: Unusual failure of shm_open with O_RDWR! Message: Permission denied
            at com.skaggsm.sharedmemory.SharedMemoryTest$1$4.invokeSuspend(SharedMemoryTest.kt:69)
            ... 2 more

            Caused by:
            java.lang.RuntimeException: Unusual failure of shm_open with O_RDWR! Message: Permission denied
                at com.skaggsm.sharedmemory.posix.SharedMemoryPOSIX.<init>(SharedMemoryPOSIX.java:40)
                at com.skaggsm.sharedmemory.SharedMemory.getSharedMemory(SharedMemory.java:34)
                at com.skaggsm.sharedmemory.SharedMemoryTest$1$4$1.invokeSuspend(SharedMemoryTest.kt:75)
                at com.skaggsm.sharedmemory.SharedMemoryTest$1$4$1.invoke(SharedMemoryTest.kt)
                at com.skaggsm.sharedmemory.SharedMemoryTest$1$4$1.invoke(SharedMemoryTest.kt)
                at io.kotest.property.internal.ProptestKt$proptest$3$2.invokeSuspend(proptest.kt:32)
                at io.kotest.property.internal.ProptestKt$proptest$3$2.invoke(proptest.kt)
                at io.kotest.property.internal.ProptestKt$proptest$3$2.invoke(proptest.kt)
                at io.kotest.property.internal.TestKt.test(test.kt:21)
                at io.kotest.property.internal.ProptestKt.proptest(proptest.kt:31)
                at io.kotest.property.PropertyTest1Kt.checkAll(propertyTest1.kt:16)
                ... 3 more
```

**Comment by magneticflux-** [comment]
This is what went wrong:
Apple changed the signature of `shm_open` from
```c
int shm_open(const char *name, int oflag, mode_t mode);
```
to
```c
int shm_open(const char *name, int oflag, ...);
```
so that the `mode` parameter could be optional since it's only used if `O_CREAT` is specified as an `oflag`.

Replacing the last parameter with varargs coincidentally works on x86_64 because of the calling convention (sometimes varargs can go in registers), but that completely fails on ARM which requires that all varargs to go on the stack instead of in registers.

My code called `shm_open` and put three parameters in registers. On Linux, all three are used. On macOS x86_64, all three are used. On macOS aarch64, only the first two are used, meaning that the shared memory is created with no permissions.
